### ISSUE TITLE
No hint path defined for [Winter.User] error

### ISSUE THREAD

**Issue by damiaaann** [rluders/wn-jwtauth-plugin#63]
Hey,

I noticed that [this](https://github.com/rluders/oc-jwtauth-plugin/blob/3f29aa808465a976f9e8c32b8515fd7b79c29ebf/http/controllers/ForgotPasswordController.php#L64) line returns an error because the hint path is wrong. Only issue with it, is that the path should be all in lowercase.

**Comment by Pok09** [comment]
Installing [BUILDER](https://github.com/wintercms/wn-builder-plugin) fixed this error for me

**Comment by rluders** [comment]
@damiaaann I guess that it is actually a but. It probably must be lowercase.
