### ISSUE TITLE
Class '\RLuders\JWTAuth\Providers\AuthServiceProvider' not found

### ISSUE THREAD

**Issue by kostyabizin** [rluders/wn-jwtauth-plugin#66]
Hi!

Help me please. I'm currently learning winter cms(Watch and Learn) and there using your plugin. I tried to install it from cms backend, but failed. Then install by composer and it gives out such a mistake... 2 days I have been trying to understand what he wants from me

**Comment by Hoodognik** [comment]
+

**Comment by Pok09** [comment]
Install Tymon/jwt-auth on composer, or do Simply `composer update` on the root of the project
