### ISSUE TITLE
Support to Winter CMS 1.2 with Laravel 9

### ISSUE THREAD

**Issue by rluders** [rluders/wn-jwtauth-plugin#67]
Now that [Winter CMS 1.2 now supports Laravel 9](https://wintercms.com/blog/post/v12-laravel-9-support-now-available), and `tymon/jwt-auth` seems to be totally abandoned, we need to replace it with `php-open-source-saver/jwt-auth` that is a fork from the tymon's librabry but with support to Laravel 9.

**If you are using Winter CMS 1.2 and having issues with the plugin let me know on this issue, 'cause this could be the main reason.**

**Comment by josephcrowell** [comment]
Yes I tried to do an upgrade to 1.2 and everything broke down. I was even getting internal server errors loading the backend. This is probably on major reason why, although I probably need to do upgrades in some of my plugins as well.

**Comment by josephcrowell** [comment]
On a side note, I'm guessing that the CORS plugin won't be necessary now since base Winter is now using a JSON api for it's backend?

**Comment by math-u** [comment]
Hi! Any progress with the plugin to support Laravel 9? I am trying to use it with new October but having errors.

**Comment by bkrajendra** [comment]
getting error Declaration of RLuders\JWTAuth\Exceptions\JsonValidationException::getStatusCode()

**Comment by bkrajendra** [comment]
Any update on this?

**Comment by rluders** [comment]
I've been away from Laravel + Winter CMS for a while... PR to fix this issue is more than welcome.

**Comment by bkrajendra** [comment]
@rluders 
I managed to fix the above issue but am now stuck in endless CORS issues.
Mostly I resolve it... but this time does not understand what the issue can be.
I have exact same plugin code deployed in another server with WinterCms, but I am not able to go ahead due to the CORS issue.
the only difference is working server has PHP 7.4 and this new one has 8+

**Comment by rluders** [comment]
@bkrajendra are you also using the https://github.com/rluders/wn-cors-plugin?

**Comment by bkrajendra** [comment]
No, i am not using this. I earlier tried this but does not help. I use angular as frontend, I also need error responses to have proper cors, so I prefer adding manually adding to those conditions, I know this is not a proper way to do it. 
I'll again try this plugin, as I have not tried it with wintercms.

**Comment by bkrajendra** [comment]
Hi @rluders , With the use of wn-cors-plugin, all working fine now.
I have submitted the PR for the changes I made to migrate the plugin to php-open-source-saver/jwt-auth.
Please review and merge it.

**Comment by bkrajendra** [comment]
@rluders can you please review and merge the PR.?

**Comment by rluders** [comment]
@bkrajendra yep, I will, just need to wait a little bit, I just returned from my vacation. But, I'll review it ASAP, not sure if today or during the week.

**Comment by rluders** [comment]
@bkrajendra PR merged. It should be good now. If someone found any issue, please let me know by opening another issue.
